//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerliftingIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Athletes
    {
        public Athletes()
        {
            this.Results = new HashSet<Results>();
            this.TrainingAthletes = new HashSet<TrainingAthletes>();
        }
    
        public int AthleteId { get; set; }
        public string FullName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int RankId { get; set; }
        public int WeightCategoryId { get; set; }
        public int CoachId { get; set; }
    
        public virtual Coaches Coaches { get; set; }
        public virtual Ranks Ranks { get; set; }
        public virtual WeightCategories WeightCategories { get; set; }
        public virtual ICollection<Results> Results { get; set; }
        public virtual ICollection<TrainingAthletes> TrainingAthletes { get; set; }
    }
}
