//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerliftingIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coaches
    {
        public Coaches()
        {
            this.Athletes = new HashSet<Athletes>();
            this.Trainings = new HashSet<Trainings>();
        }
    
        public int CoachId { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public int Experience { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<Athletes> Athletes { get; set; }
        public virtual ICollection<Trainings> Trainings { get; set; }
    }
}
