//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerliftingIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competitions
    {
        public Competitions()
        {
            this.Results = new HashSet<Results>();
        }
    
        public int CompetitionId { get; set; }
        public string CompetitionName { get; set; }
        public System.DateTime CompetitionDate { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<Results> Results { get; set; }
    }
}
