//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerliftingIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercises
    {
        public Exercises()
        {
            this.Results = new HashSet<Results>();
        }
    
        public int ExerciseId { get; set; }
        public string ExerciseName { get; set; }
    
        public virtual ICollection<Results> Results { get; set; }
    }
}
