//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerliftingIS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PowerliftingDBEntities : DbContext
    {
        public PowerliftingDBEntities()
            : base("name=PowerliftingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Athletes> Athletes { get; set; }
        public DbSet<Coaches> Coaches { get; set; }
        public DbSet<Competitions> Competitions { get; set; }
        public DbSet<Exercises> Exercises { get; set; }
        public DbSet<Ranks> Ranks { get; set; }
        public DbSet<Results> Results { get; set; }
        public DbSet<TrainingAthletes> TrainingAthletes { get; set; }
        public DbSet<Trainings> Trainings { get; set; }
        public DbSet<WeightCategories> WeightCategories { get; set; }
    }
}
