//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerliftingIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainings
    {
        public Trainings()
        {
            this.TrainingAthletes = new HashSet<TrainingAthletes>();
        }
    
        public int TrainingId { get; set; }
        public System.DateTime TrainingDate { get; set; }
        public int CoachId { get; set; }
        public string Description { get; set; }
    
        public virtual Coaches Coaches { get; set; }
        public virtual ICollection<TrainingAthletes> TrainingAthletes { get; set; }
    }
}
