//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerliftingIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingAthletes
    {
        public int TrainingAthleteId { get; set; }
        public int TrainingId { get; set; }
        public int AthleteId { get; set; }
    
        public virtual Athletes Athletes { get; set; }
        public virtual Trainings Trainings { get; set; }
    }
}
