//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerliftingIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightCategories
    {
        public WeightCategories()
        {
            this.Athletes = new HashSet<Athletes>();
        }
    
        public int WeightCategoryId { get; set; }
        public string CategoryName { get; set; }
        public decimal MaxWeight { get; set; }
    
        public virtual ICollection<Athletes> Athletes { get; set; }
    }
}
